package = "hash-compression"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = "Wrapper repo for static video compression project."
maintainer = "Sean Allesina-McGrory"
labels = [  ]
license = "BSD-2-Clause"

[dependencies]
# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = [ "src/main.lua" ]

[build]
type = "builtin"
